name = "Vonge-for-Apps"
description = "Vonge is a Personal portfolio/blog site template"
tags = []
license = "MIT"
homepage = "https://github.com/appimage-sig/vonge-zola-theme/"
min_version = "0.4.0"

[extra]
logo_image = "images/logo.svg"
social_media_share_image = "/images/01.jpg"
disqus_identifier = ""
twitter_handle = ""

author_image = '/images/avatar.jpg'

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/apps", title = "Apps" },
    { url = "", title = "Categories", submenu = [
        { url = "$BASE_URL/categories/audiovideo", title = "Audio & Video" },
        { url = "$BASE_URL/categories/development", title = "Development" },
        { url = "$BASE_URL/categories/finance", title = "Finance" },
        { url = "$BASE_URL/categories/games", title = "Games" },
        { url = "$BASE_URL/categories/graphics", title = "Graphics" },
        { url = "$BASE_URL/categories/network", title = "Network" },
        { url = "$BASE_URL/categories/productivity", title = "Productivity" },
        { url = "$BASE_URL/categories/science", title = "Science" },
        { url = "$BASE_URL/categories/system", title = "System" },
        { url = "$BASE_URL/categories/utility", title = "Utility" },
    ] }
]

social_icons = [
    { url = "https://github.com/cydave", icon = "GitHub" },
    { url = "https://twitter.com/_cydave", icon = "Twitter" },
    { url = "$BASE_URL/atom.xml", icon = "RSS" },
    { url = "https://pinterest.com", icon = "Pinterest"},
]

date_format = "%d %b %Y"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]

[extra.footer]
menu = [
    { url = "$BASE_URL", title = "Home" },
        { url = "$BASE_URL/categories/audiovideo", title = "Audio & Video" },
        { url = "$BASE_URL/categories/development", title = "Development" },
        { url = "$BASE_URL/categories/finance", title = "Finance" },
        { url = "$BASE_URL/categories/games", title = "Games" },
        { url = "$BASE_URL/categories/graphics", title = "Graphics" },
        { url = "$BASE_URL/categories/network", title = "Network" },
        { url = "$BASE_URL/categories/productivity", title = "Productivity" },
        { url = "$BASE_URL/categories/science", title = "Science" },
        { url = "$BASE_URL/categories/system", title = "System" },
        { url = "$BASE_URL/categories/utility", title = "Utility" },
]
#copyright = ""

[[extra.content_blocks]]
block = "blog-section"
title = "Recent Posts"
description_html = """
    <p>Vonge blog features productivity, tips, inspiration and strategies for
    massive profits. Find out how to set up a successful blog or how to make
    yours even better!</p>"""
link_url = "/posts"
show_posts = true


[author]
name = "Pascal Berrang"
homepage = "https://pascal-berrang.de"

[original]
author = "CloudCannon"
homepage = "https://cloudcannon.com/templates/vonge/"
repo = "https://github.com/CloudCannon/vonge-hugo-bookshop-template"
